### ISSUE TITLE
Multiple Resting positions in Tic Tac Toe

### ISSUE THREAD

**Issue by geoknee** [magmo/apps#153]
At the moment the "play again" flow involves both players broadcasting near identical "resting" positions. This makes it difficult for a simple (memoryless) bot to decide what to broadcast next. Furthermore, the `validTransition` function for Tic Tac Toe does not treat the `Resting -> Resting` case. 

We need an even number of messages sent between `Victory` (or `Draw`) and `Xplaying` in order for a "loser plays first" implementation. 

One solution is to make the even number 0. Although this would seem to remove opportunities for players to reject proposed games, 
- Tic Tac Toe relies on at least one player being willing to go second (otherwise, strictly rational players would never start a game).*
- By funding the game in the first place, Player B has already committed to going second (in the first round at least).

A welcome side effect will be a simplification of the channel state machine and underlying code. A rough state machine might look like this: 
![Screenshot 2019-02-04 at 18.06.49.png](https://zube.io/files/magmo/7ea3a3ca1ff69c028248ed5342df5907-screenshot-2019-02-04-at-18-06-49.png)

*There are solutions to this, for example forcing a round of tic tac toe to actually be two rounds, with each player going first exactly once. At the moment I consider this an unnecessary complication, which would take us beyond what we are setting out to achieve.

**Comment by geoknee** [comment]
I would fix this before tackling magmo/apps#128.

**Comment by geoknee** [comment]
- write new test-scenarios which do not involve `Resting`
- update `validTransition`  to not reference resting and to make things as fair as possible
- update reducers (and dependencies) to not send `Resting` messages.

**Comment by tomclose** [comment]
An important factor here is the penalty for resigning. If a player can resign without penalty during play, then we don't need the resting state. But I think we normally treat a resignation during play as a forfeit.

Consider the following sequence of events:

* A finishes the game by making the winning move
* B's move is to start a new game, picking their initial move
* A wants to quit and bank their winnings, but can't

This is bad, as the winner is forced into playing again. One of the advantages of a multi-round game like tic-tac-toe is that you can limit your exposure to griefing by giving a neutral 'out' between games. In the situation above, there wasn't a neutral 'out'.

There are a couple of ways around this.

One way would be to introduce a "win and resign" state, which A could move to instead of moving to the regular winning state. This would work, but probably wouldn't fit with the game flow because the player would either need to make the decision before the final move (which is weird for the winner) or the app would need to withhold a winning move until the winner has made the play again decision (which causes a delay for the loser).

A different way is to split out the resting states:

`Victory` -> `Resting1` -> `Resting0` -> `XMoves`

If we wanted the winner to play first, then we'd only need the `Resting0` state. I guess you could think of transitioning to `Resting1` as "I want to play again but I'm going first" and a transition to `Resting0` as "I want to play again and you go first". You could even extend the rules so that `Victory` -> `Resting0` is also allowed, so that the loser actually gets to choose whether they want to go first or not.

**Comment by tomclose** [comment]
You could even name `Resting1` = `PlayAgainMeFirst` and `Resting0` = `PlayAgainYouFirst`.

**Comment by geoknee** [comment]
Good point, @tomclose . I was thinking we could have special rules for transitioning to `Conclude` from `XPlaying`, where if no noughts have been placed then we can exit without penalty. But thinking about it some more, I like your suggestion of two different types of `PlayAgain`  state, which will make the resulting `validTransition` function cleaner and easier to understand.
