### ISSUE TITLE
Cannot respond to challenge at play again state

### ISSUE THREAD

**Issue by lalexgap** [magmo/apps#178]
In TTT when waiting for the other play to select play again you can issue a challenge. 

The challengee is alerted to the challenge and can select the `respond with `move` option but when they select play again they get stuck waiting for the other player.
Screen Shot 2019-02-08 at 12.45.51 PM.png![image.png](https://zube.io/files/magmo/f2f4f43d3233107901e83bfb0ecb35b6-image.png)

**Comment by lalexgap** [comment]
@geoknee I was able to reproduce this on master today by:
- Completing a game.
- Player A selects play again.
- Player A initiates a challenge.
- Player B gets challenge and selects respond with move
- Player B selects play again.

No transaction gets sent to the adjudicator and the players are stuck waiting for the challenge to expire.

**Comment by geoknee** [comment]
@lalexgap it's weird, I could have sworn I'd fixed this. Digging into it a bit, the problem is far from clear to me. I also tried challenging in a regular, 'Wait To Pick Move' state and that doesn't work either. 

Furthermore, challenging in rps also doesn't work, although this could be for different reasons: 
![screenshot 2019-02-12 at 09 26 59](https://user-images.githubusercontent.com/1833419/52625332-ac344180-2ea8-11e9-80aa-c0e561aa6a08.png)

The challengee acknowledges the challenge, clicks respond with move, wallet hides itself, then clicking a move hexagon does nothing.

**Comment by geoknee** [comment]
I believe this is the offending line of code 

https://github.com/magmo/apps/commit/574af21083b756df03365de69bb76f583c7dd8b9#diff-0cc9ed817cea46dca936a5936ff6ff0cR10

It was introduced recently, which explains why I thought this issue was fixed. 

Of course, this line of code does not seem incorrect. We just need to set the type of the message to include the string 'WALLET'.
