### ISSUE TITLE
Tag the last working commit of the mono repo

### ISSUE THREAD

**Issue by kerzhner** [magmo/apps#289]
Work for ledger channels is going directly into the `master` branch. The RPS app will not be functional for at least this sprint (and potentially longer). It would be good to have a reference for the last commit where the app is fully functional. Git tags is probably the best way to do this.

**Comment by geoknee** [comment]
This could be useful, but the tricky thing is trying to find the *most recent* commit where the app is functional. Far easier to stick a tag on the most recent deploy, which is more out of date but we know it works. 

It might be good to get into a habit of putting these tags in immediately before all the breaking changes are made, rather than retrospectively.

**Comment by kerzhner** [comment]
@geoknee We probably don't need to tag the last deployed commit since we are using the `deploy` branch for auto deploys. While knowing what commit is deployed (and, presumably, fully functional) is somewhat independent from the "last known working commit," it is probably sufficient information in case we need to patch an issue with the deployed app.

If you agree, we can archive this issuel

**Comment by geoknee** [comment]
@kerzhner I agree!
