### ISSUE TITLE
Adjudicator syncing

### ISSUE THREAD

**Issue by tomclose** [magmo/apps#384]
For several protocols (e.g. challenging and responding) it would be useful to have the state of the adjudicator in the redux store. The format would be something like:
```ts
interface Adjudicator {
    [channelId: string]: OnChainChannelState;
}

interface OnChainChannelState {
    balance: number; // or string or bigint or whatever
    outcome?: { destination: string, total: number }[];
    challenge?: { expiry: number, state: ChannelState };
}
```
The adjudicator syncer would be responsible for:

* Keeping the `Adjudicator` data up-to-date (for all `channelId`s in the `channelStore`)
* Triggering a `CHALLENGE_DETECTED` when a challenge is added to a channel.
* Triggering a `CHANNEL_FINALIZED` (a new action) when the outcome is finalized (either from a channel expiring or from a conclusion proof being presented).
* Triggering a `FUNDING_CHANGED` when a channel's balance changes
* Triggering an `OUTCOME_CHANGED` when the outcome changes (due to a `claim` or `transfer`)
* ... possibly some other things

Unanswered question: how do we route these actions to the right process? Do we just use the existing `channelId` subscription in the `Process` object?

**Comment by lalexgap** [comment]
@tomclose Thinking about this I'm not sure we want a saga. Sagas can't update state (as far as I remember) that's the responsibility of the reducer. I

That just leaves triggering these actions and that seems like it might be a better fit for the `adjudicator-watcher`.  It already handles `CHALLENGE_DETECTED` and part of `CHANNEL_FINALIZED` (The concluded event) and it could be expanded to handle these future actions (assuming we throw an event in the adjudicator) 

I think we may just want an `ajudicatorStateReducer` that handles actions triggered by `adjudicator-watcher` and updates the `AdjudicatorState`. What are your thoughts?

**Comment by tomclose** [comment]
Seems reasonable to extend the `adjudicator-watcher` to do this. We will definitely also need an `adjudicatorStateReducer`. One thing I'm not quite sure about is when /  how we send an action to the processes. I guess the adjudicator watcher could do this too? Do we need to ensure that the `adjudicator-state` is updated before the process is pinged and, if so, can we do this?

**Comment by lalexgap** [comment]
## Updating State
I think we'll need to enforce that `adjudicatorState` gets updated before `protocolReducers` run. I think this is the same case as `channelState`.
So I think we need two stages in our root reducer.
- run reducers that update state in sharedData
- run protocol reducers

## Routing To Processes
I think we have most of the plumbing for this already.

For running processes (say `FUNDING`) actions generated by the `adjudicator-watcher` should get routed to the correct process already (based on `channelsToMonitor` on the `processState`.)

For adjudicator events that should create a new process we could always dispatch them with just a `channelID`. The `routeToNewProcessInitializer` function in the root reducer would handle these events and create a new process.

The only tricky bit is if we want an adjudicator event to be routed to a process if it exists otherwise create a new process. However this seems similar to when we receive a message early for funding and can probably be handled in the same way

### Open Questions
If processes only run
