### ISSUE TITLE
End-to-end testing of SimpleAdjudicator

### ISSUE THREAD

**Issue by geoknee** [magmo/apps#69]
input -> output tests of contracts that use the rps and/or ttt game libraries

While the `fmg-simple-adjudicator` package has good tests, they implement only a very simple game library (namely a Counting Game). 

If those tests pass, *and* the game-specific `validTransition` function is also passing thorough tests, this ought to give us confidence that the whole thing works. However, end-to-end testing will give us more confidence and should help troubleshoot problems such as not getting refunded from a channel. Without the end-to-end tests, we couldn't be sure if the contracts were at fault, or simply that the app is not preparing the transactions correctly.

**Comment by geoknee** [comment]
In the short term this should be narrowed down to testing withdraw functionality of simple adjudicator. May want to revisit some of the tests included in v0.1.6 .

**Comment by andrewgordstewart** [comment]
The current test-scenarios setup make this difficult to test, since the library address is a constant in the test scenarios. (Fetching the correct library address is an async process, and is not possible to do for a static set of test scenarios.)

This is a problem I ran into in force-move, and my solution was to not write test-scenarios, but to explicitly define the states in the test file. (There are more test files in the rps/ttt packages, which makes that strategy untenable here.)

We could, for the moment, deal with the overhead of defining states in the adjudication integration tests.
